# OSEMN Exercises

In [1]:
%matplotlib inline
import pandas as pd
import numpy as np

1\. Create a random list of number and then save it to a text file named "simple_data.txt"

In [19]:
import numpy.random as npr
npr.seed(1187163)
simpledata = [npr.rand() for i in range(0,100)]
simpledata = np.array(simpledata)
print ("simple data:","\n",simpledata,"\n" )

simplename = 'simple_data.txt'
with open('simple_data.txt', 'w') as f:
    print("#", simplename,file=f)
    for i in range(0,len(simpledata)):
        print(simpledata[i], file=f)

simple data: 
 [0.8765887  0.98849261 0.96817361 0.64784406 0.55442852 0.33099578
 0.61836705 0.92019021 0.82863804 0.82886953 0.97379684 0.09204352
 0.12152554 0.2982897  0.34796226 0.19904243 0.64592899 0.90824288
 0.04760195 0.61546417 0.52745333 0.37241116 0.01761652 0.70446205
 0.24301878 0.56730628 0.03242647 0.86475833 0.00977616 0.51446964
 0.20374266 0.58388841 0.82954232 0.99733426 0.61758466 0.33543805
 0.22333179 0.15763204 0.02193412 0.84937837 0.32423215 0.99485674
 0.2420767  0.17365034 0.62074661 0.86521222 0.37939368 0.31214468
 0.96897424 0.71415689 0.18765036 0.59611222 0.84356375 0.66204127
 0.51544939 0.55682469 0.66343128 0.63380941 0.51116871 0.96881604
 0.31050779 0.23245157 0.67537437 0.38001502 0.94403634 0.05592544
 0.33221719 0.99992998 0.61965085 0.02299042 0.1503989  0.47711845
 0.35859136 0.56392865 0.29603364 0.04792043 0.61209545 0.12252967
 0.72141138 0.15742231 0.99056498 0.93160086 0.19681974 0.71869874
 0.54086458 0.99263573 0.86437663 0.99216551 0.

2\. Create a random matrix of 5x5 and then save it to a text file named "data.txt"

In [31]:
data55 = np.array([[npr.rand() for i in range(0,5)] for j in range(0,5)])
print(data55)
print("shape",data55.shape)

name55 = 'data.txt'
with open('data.txt', 'w') as f:
    print("#",name55,file=f)
    for i in range(0,len(data55)):
        for j in range(0,len(data55)):
            print(data55[i][j], end=' ', file=f)
        print('',file=f)
print(data55[0][4])

[[0.16899632 0.21837894 0.87593822 0.72696791 0.60944196]
 [0.84784263 0.72396952 0.78772989 0.62415597 0.68690058]
 [0.31993408 0.10000498 0.84084402 0.12981277 0.48149876]
 [0.31010138 0.13643499 0.09630053 0.17472705 0.53527965]
 [0.28774834 0.73579671 0.9501307  0.45181758 0.53500769]]
shape (5, 5)
0.6094419595361918


3\. Load the saved txt file of point 2 and convert it to a csv file (by hand)

In [39]:
import csv

read55 = np.loadtxt(name55, comments='#')
print(read55)

#with open(simplenamec, 'w', newline='') as f: #all in one row
#    wr = csv.writer(f)
#    wr.writerow(readsimple)
    
#newline for each line
np.savetxt('data55a.csv', read55, delimiter=",", fmt='%s')   

with open('data55.csv', 'w') as f:
    print("#",name55,file=f)
    for i in range(0,len(read55)):
        for j in range(0,len(read55)):
            print(data55[i][j], end=',', file=f)
        print('',file=f)
print(data55[0][4])

[[0.16899632 0.21837894 0.87593822 0.72696791 0.60944196]
 [0.84784263 0.72396952 0.78772989 0.62415597 0.68690058]
 [0.31993408 0.10000498 0.84084402 0.12981277 0.48149876]
 [0.31010138 0.13643499 0.09630053 0.17472705 0.53527965]
 [0.28774834 0.73579671 0.9501307  0.45181758 0.53500769]]
0.6094419595361918


4\. load the binary file named *credit_card.dat* and convert the data into the real credit-card number.
Each line correspond to a credit card number.
Each character is composed by 6 bit (even the space) and the last 4 bit are just a padding

**hint**: use the `chr()` function to convert a number to a char

5\. Load the file "user_data.json", filter the data by the "CreditCardType" field equals to "American Express". Than save the data a to CSV.

6\. Load the file from this url: [https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1](https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1) with Pandas. 
+ Explore the data (see the info of the data)
+ Draw the istogram of the 'class' field. Decribe wath yuou see


7\. Load the remote file [https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1](https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1) with Pandas and plot a scatter plot all possible combination of the following fields:
    
  + features_1
  + features_2
  + features_3

8\. Load the same file of point 6, and convert the file to json with Pandas.